#!/bin/sh

defaultManager="yah649a5h1ce.cloud.wazuh.com"
defaultPassword="default_password"

get_wazuh_manager()
{
        manager="$(snapctl get manager)"
        if [ -z "$manager" ]; then
                manager="$defaultManager"
                set_wazuh_manager $manager
        fi
        echo "$manager"
}

set_wazuh_manager()
{
        echo "Inside set_wazuh_manager with parameter: $1"
        snapctl set manager="$1"
}

get_wazuh_registration_password()
{
        password="$(snapctl get password)"
        if [ -z "$password" ]; then
                password="$defaultPassword"
                set_wazuh_registration_password $password
        fi
        echo "$password"
}

set_wazuh_registration_password()
{
        echo "Inside set_wazuh_registration_password with parameter: $1"
        snapctl set password="$1"
}