#!/bin/sh

DEFAULT_WAZUH_MANAGER="yah649a5h1ce.cloud.wazuh.com"
DEFAULT_WAZUH_REGISTRATION_PASSWORD="default_password"

wazuh_manager()
{
        manager="$(snapctl get WAZUH_MANAGER)"
        if [ -z "$manager" ]; then
                manager="$DEFAULT_WAZUH_MANAGER"
                set_wazuh_manager $manager
        fi
        echo "$manager"
}

set_wazuh_manager()
{
        echo "Inside set_wazuh_manager with parameter: $1"
        snapctl set WAZUH_MANAGER="$1"
}

wazuh_registration_password()
{
        password="$(snapctl get WAZUH_REGISTRATION_PASSWORD)"
        if [ -z "$password" ]; then
                password="$DEFAULT_WAZUH_REGISTRATION_PASSWORD"
                set_wazuh_registration_password $password
        fi
        echo "$password"
}

set_wazuh_registration_password()
{
        echo "Inside set_wazuh_registration_password with parameter: $1"
        snapctl set WAZUH_REGISTRATION_PASSWORD="$1"
}