#!/bin/sh

defaultWazuhManager="yah649a5h1ce.cloud.wazuh.com"
defaultWazuhRegistrationPassword="default_password"

get_wazuh_manager()
{
        manager="$(snapctl get wazuhManager)"
        if [ -z "$manager" ]; then
                manager="$defaultWazuhManager"
                set_wazuh_manager $manager
        fi
        echo "$manager"
}

set_wazuh_manager()
{
        echo "Inside set_wazuh_manager with parameter: $1"
        snapctl set wazuhManager="$1"
}

get_wazuh_registration_password()
{
        password="$(snapctl get wazuhRegistrationPassword)"
        if [ -z "$password" ]; then
                password="$defaultWazuhRegistrationPassword"
                set_wazuh_registration_password $password
        fi
        echo "$password"
}

set_wazuh_registration_password()
{
        echo "Inside set_wazuh_registration_password with parameter: $1"
        snapctl set wazuhRegistrationPassword="$1"
}