#!/bin/sh
# source the management script
. "$SNAP/bin/management-script"

# Call the function wazuh_manager from the management script
WAZUH_MANAGER="$(wazuh_manager)"
# Call the function wazuh_registration_password from the management script
WAZUH_REGISTRATION_PASSWORD="$(wazuh_registration_password)"
export WAZUH_MANAGER
export WAZUH_REGISTRATION_PASSWORD

var/ossec/bin/wazuh-control start
# "$SNAP/bin/wazuh-control start"