#!/bin/sh
# source the management script
. "$SNAP/management-script"

# Call the function wazuh_manager from the management script
WAZUH_MANAGER="$(get_wazuh_manager)"
# Call the function wazuh_registration_password from the management script
WAZUH_REGISTRATION_PASSWORD="$(get_wazuh_registration_password)"
export WAZUH_MANAGER
export WAZUH_REGISTRATION_PASSWORD

$SNAP/var/ossec/bin/wazuh-control start